name: Update Workflow From Text File

on workflow_dispatch:
  jobs:

    - name: Read workflow instructions from text file
      run: python3 -m read_update.js

events:
  workflow_dispatch:
  - type: workflow_dispatch

  workflow_dispatch:
    type: workflow_dispatch